### ISSUE TITLE
Support Markdown for document

### ISSUE THREAD

**Issue by zjkmxy** [UCLA-IRL/ndn-workspace-solid#125]
There are requests on supporting Markdown documents. Let's discuss about this.

## Background

Currently, the rich document is of XML format, which is supported by [Tiptap](https://tiptap.dev/docs) core and several extensions, and rendered as HTML.

### Reason Markdown was not used

Consider the following case:
```markdown
#section 1
Some text.
```
Suppose Alice injected another section title:
```markdown
#section 1
#section 2
Some text.
```
And Bob wrote some text into the existing section:
```markdown
#section 1
Write more. Some text.
```
Then, in the worst case, the final result will be
```markdown
#section 1
#section 2Write more. 
Some text.
```
This is because when a user inserts a Markdown section, one usually presses Enter to insert the line break first, and then goes back to write the title.
However, a lot of CRDT implementations (including Yjs) have problems handling text inserted in reverse order.
Therefore, in the CRDT's view, Alice made *two separate* changes.
And since they are non-continuous, Bob's change may be put in the middle of them.
This leads to the strange result.
This does not apply to XML documents, because the section title is surrounded with XML tags, which are specially handled by CRDT to make sure others' changes cannot easily get into the tag pairs.

### Benefits of Markdown

- Largely adopted.
- Internal data structure is plain text, so it can support exporting the file content as plain text and then importing back.
  - Current XML Rich doc impl does not allow you to import the XML file back. Since XML fragment used in Yjs requires the input to form a tree structure, it will take a lot of effort to reconstruct it.

## Editor Candidates

Unfortunately TipTap does not support Markdown, so we need another editor.
We may have two workflows: (1) WYSIWYG, with one panel showing the Markdown result which is also editable; (2) LaTeX-like two-panel mode, one showing the editable Markdown source and the other showing the rendered result.
There are a lot of WYSIWYG editors like:
- [Milkdown](https://milkdown.dev/)
  - This one has a Yjs plugin: https://milkdown.dev/docs/guide/collaborative-editing
- [StackEdit](https://stackedit.io/)
- [TOAST UI Editor](https://ui.toast.com/tui-editor)

## Things to consider

- What is the general workflow the editor suggests?
- Does it have CRDT backend support?
- Prosemirror backed editors are preferred. Since TipTap is also based on Prosemirror, this reduces the duplicated code size.
- Can users write plain Markdown notations or they have to use provided editing UI?
- Does it have plugins to extend?

**Comment by zjkmxy** [comment]
We decided that the issue described here is not a big deal and we plan to move forward with Markdown support.

**Comment by zjkmxy** [comment]
See new branch: https://github.com/UCLA-IRL/ndn-workspace-solid/tree/markdown

TODOs before merge:
- Improve the UI. The current editor looks very ugly.
- If possible, remove Tailwind CSS and use the existing stuff. I don't want to import duplicate things. SA: https://milkdown.dev/docs/guide/styling#writing-your-own-theme
- There is a GitHub-flavour plugin, but it depends on remark-gfm 4.0. The chat Markdown is incompatible with this version (#127). Seek a way to handle this.

**Comment by AnoldGH** [comment]
> There is a GitHub-flavour plugin, but it depends on remark-gfm 4.0. The chat Markdown is incompatible with this version (https://github.com/UCLA-IRL/ndn-workspace-solid/issues/127). Seek a way to handle this.

I pushed an update in #132 so the old version of `remark-gfm` is aliased now, this should resolve this incompatibility.
