### ISSUE TITLE
Collaborate with NDN repo

### ISSUE THREAD

**Issue by zjkmxy** [UCLA-IRL/ndn-workspace-solid#20]
Currently all data are stored in users browser. How could we make use of NDN repo (such as [ndn-python-repo](https://ndn-python-repo.readthedocs.io/en/latest/index.html)) to support online storage?
We need to separate backend code with the frontend and write a NodeJS / Deno daemon to stay in sync and issue commands to the repo to store synced objects.
Also, if the repo is not supposed to be a legit producer of the workspace, it also needs to store SVS Sync Interests, because it is not able to sign it.

**Comment by yoursunny** [comment]
NDNts support for ndn-python-repo is broken at the moment.
https://github.com/UCLA-IRL/ndn-python-repo/issues/60#issuecomment-1258879413

**Comment by zjkmxy** [comment]
That's not something I am able to handle ...
Theoretically I'm maintaining the codebase of ndn-python-repo, but I'm not in the project where the repo is currently being used, and those design decisions till now were not proposed by me.
I can write some ad hoc code to interact with it for now.

**Comment by yoursunny** [comment]
NDNts has its own repo, you know.
There's a `@ndn/repo` package implementing packet storage and `@ndn/repo-cli` running it as service.
I can add other features if needed.

**Comment by zjkmxy** [comment]
Fixed in UCLA-IRL/ndn-python-repo#94
