### ISSUE TITLE
Check workbox for offline support

### ISSUE THREAD

**Issue by zjkmxy** [UCLA-IRL/ndn-workspace-solid#21]
Currently workbox does not work as we want. For example:
- It may cache pages like `/profile` and tries to fetch it from the server. But this page is served by Solid Router and does not exist on the server side.
- It does not cache fonts and background pictures, which make the offline version look very different.
- For A-Frame, I don't want to put it in my server. It is too large. How can the workbox cache the CDN version of its source code?

**Comment by yoursunny** [comment]
> How can the workbox cache the CDN version of its source code?

If the A-Frame CDN allows cross-domain `fetch` and you can find out URLs of every resource needed, it's possible to cache all the resources.
Caution that browser may impose a list of how much cache storage can be used of a PWA.

**Comment by zjkmxy** [comment]
I'm not much worried of the disk storage. In the worst case we can use OPFS to get rid of it, whose capacity is in proportion to the disk size.

**Comment by zjkmxy** [comment]
Solved in 6885abd
