### ISSUE TITLE
Add test

### ISSUE THREAD

**Issue by zjkmxy** [UCLA-IRL/ndn-workspace-solid#27]
I know there are some frameworks allowing people to test browser apps. The problem is when and who.
Opened this issue for project management and task assignment.

**Comment by yoursunny** [comment]
There are only two options to test in real browser: Puppeteer and Selenium.
Puppeteer is easier to program, but it only supports latest Chrome and Firefox.
Selenium is more difficult, but it supports more browsers and control physical/virtualized mobile devices (Sauce Labs offers them).

**Comment by minruigui** [comment]
It appears that the project only supports the latest browsers. Is anyone currently handling this task? If not, may I use Puppeteer to write browser tests?

**Comment by zjkmxy** [comment]
> It appears that the project only supports the latest browsers. Is anyone currently handling this task? If not, may I use Puppeteer to write browser tests?

We will not have browser tests since it is hard to write and easy to be broken.
However, we have separated the backend out of this repo as a stand-alone library: https://github.com/UCLA-IRL/ndnts-aux

We will add tests to that library. You are welcome to contribute to it.
