### ISSUE TITLE
Compile PDF file

### ISSUE THREAD

**Issue by zjkmxy** [UCLA-IRL/ndn-workspace-solid#5]
https://github.com/zjkmxy/ndn-workspace-solid/blob/3e46cb7757ff9fcdaeabd339c16a4212d175e01a/src/components/share-latex/share-latex.tsx#L169-L182

Current implementation tries to push a ZIP file to localhost's 6175 port, which is supposed to be running a LaTeX server.
We need a better design for this.

Note: the LaTeX server's code is not published. Please let me know if you need to access it.

Idea: There are two ways. Need discussion.
- Use RICE like discovery protocol, so the LaTeX server does not need to join the Sync group.
- Let the LaTeX server to join the sync group.

**Comment by yoursunny** [comment]
Is it possible to compile the LaTeX server to WebAssembly, and then run it as WebWorker?

**Comment by zjkmxy** [comment]
> Is it possible to compile the LaTeX server to WebAssembly, and then run it as WebWorker?

Yes. We have discussed this idea from beginning: https://github.com/SwiftLaTeX/SwiftLaTeX
The pros:
- Works for tablets and phones.
- Can work offline.
The cons:
- The only existing LaTeX in WASM uses AGPL license, which may affect the deployment.
- If we ship LaTeX, we need to also ship those common libraries, fonts, etc. But there are too many of them.
Therefore, we think we should try other methods first.

**Comment by pulsejet** [comment]
Ah I missed this. So I tweaked the implementation in #28 and the compilation speeds are really impressive. The initial compile times take a bit of time but my guess is that has partly to do with the package service. I believe it also already works with `usepackage` (see screenshot) and pulls libraries on demand (albeit from their server, though this should be possible to eventually fix)

I'm encouranged to push for this direction in favor of truly local-first software. Plus it seems like a nice way to show "completeness" in our retreat demo (BTW the header for bootstrapping says "Hackathon" I think we'll probably test this during retreat?)

Also we can sidestep AGPL restrictions by keeping all compiler code strictly separated (easy enough) and make it possible to build it as an optional module, similar to what ffmpeg does. Anyway, I'm actually in favor of AGPL (I don't want/see anyone commercializing any part of this) but that's not my call of course.

![image](https://github.com/UCLA-IRL/ndn-workspace-solid/assets/10709794/0f8d43f9-1a41-4637-9aa9-d8522386674f)

**Comment by zjkmxy** [comment]
Thank you for your hard work!
Yes. We will demo this in the retreat, and then consider wrapping a hackathon project.

We can separate the compiler as a downloadable module. I'm not sure about the limitation of AGPL.

**Comment by pulsejet** [comment]
Ok, great. How do you suggest to proceed? Can you review the draft PR? Actually I don't think I can make it much cleaner than it is.

**Comment by zjkmxy** [comment]
> Ok, great. How do you suggest to proceed? Can you review the draft PR? Actually I don't think I can make it much cleaner than it is.
I still prefer to set up a server... But let's discuss this on the retreat.
Will review the current code when I have time.

**Comment by zjkmxy** [comment]
Ref: [zjkmxy/ndn-workspace-compiler](https://github.com/zjkmxy/ndn-workspace-compiler/)

**Comment by zjkmxy** [comment]
Not perfect but currently working. Close for now.
Enhancement will be handled in a different issue.

**Comment by zjkmxy** [comment]
After #28 is merged, it is able to compile PDF files completely offline after caching necessary files.
I verified that I can compile even on my phone.
