### ISSUE TITLE
PDF will not compile

### ISSUE THREAD

**Issue by newsherlytemple** [UCLA-IRL/ndn-workspace-solid#64]
Hello, I was able to create my own workspace and create a file. However, the file will not compile into a PDF. I went back and reconnected to the CS217A workspace, and I wasn't able to compile that either.

**Comment by zjkmxy** [comment]
Thank you for trying this project.
Did you named your file to `main.tex`?
If it still does not compile after renaming, please provide the compilation log.

**Comment by newsherlytemple** [comment]
Found the issue, thank you!
