### ISSUE TITLE
Some difficulty downloading ndn-cxx

### ISSUE THREAD

**Issue by newsherlytemple** [UCLA-IRL/ndn-workspace-solid#65]
I was able to download ndn-cxx but on the linked page, they do not mention the git URL that the project needs to be cloned from, or the fact that it needs to be cloned prior to building. Its more of an issue with their documentation, but it might be good to include something in the "Create a Workspace" section on cloning the git repo for ndn-cxx prior to building it, especially for newer users who might not be familiar with git. Or to include the documentation directly from the git repo: https://github.com/named-data/ndn-cxx/blob/master/docs/INSTALL.rst

**Comment by zjkmxy** [comment]
Fixed.
