### ISSUE TITLE
SVS bootstrapping and fast catch-up protocol

### ISSUE THREAD

**Issue by pulsejet** [UCLA-IRL/ndn-workspace-solid#90]
Implement faster bootstrapping and catch-up when a user joins or comes back online.

Initial thoughts:
1. Every piece of data in workspace is a small CRDT delta. The slow part of the pipeline is fetching each piece of data.
2. We can just bundle all data packets into a single larger data packet and make it faster
3. When the user comes online, it hears the state vector. Subsequently they can fetch the bundle / snapshot from the entity that sent the state vector (another user or repo)
4. The bundle can be fetched using the state vector as a version number. To account for the data the user already has, we can use two state vectors as a way to fetch everything in between.

Considerations:
1. This isn't ideal since there's no history pruning (not supported by Yjs?). There may be other CRDT algorithms that can do this (see https://braid.org/antimatter)
2. Do we store "ready" bundles or build them on the fly? Performance.
3. Can we exclude the signatures from individual bundled deltas?
4. How to handle corner cases, e.g. the bundle producer does not (yet?) have all the requested data. Send partial bundle back with a longer name?

**Comment by zjkmxy** [comment]
Refer to #4

**Comment by zjkmxy** [comment]
Let's use #4 for further discussion.
