### ISSUE TITLE
Links to screenshots are broken

### ISSUE THREAD

**Issue by Pesa** [UCLA-IRL/ndn-workspace-solid#92]
![Screenshot 2024-06-07 at 1 07 27 PM](https://github.com/UCLA-IRL/ndn-workspace-solid/assets/83452/adee9f66-13dd-4d36-856d-ee13dd62057f)

**Comment by zjkmxy** [comment]
@ykocaogullar

**Comment by ykocaogullar** [comment]
Noted. I'll fix this after the finals

**Comment by Pesa** [comment]
ping

**Comment by zjkmxy** [comment]
Should be good in the latest commit. Let me have a check and then release it.

**Comment by zjkmxy** [comment]
Fixed in 4f91c5566ced96268dea6a7c737791ae072b4d53. Released in [v1.2.4](https://github.com/UCLA-IRL/ndn-workspace-solid/tree/v1.2.4).
