### ISSUE TITLE
'ValidityPeriod' Property Not Found in '@ndn/keychain'

### ISSUE THREAD

**Issue by AnoldGH** [UCLA-IRL/ndn-workspace-solid#96]
When trying to build the project I ran into an error `Property 'ValidityPeriod' does not exist on type 'typedef import(".../ndn-workspace-solid/node_modules/.pnpm/@ndn+keychain@https+++ndnts-nightly.ndn.today+keychain.tgz/node_modules/@ndn/keychain/lib/mod")'` at `ndn-testbed.tsx:109`. My `@ndn/keychain` version was `0.0.20240531-nightly-307ee4d`.

I was able to bypass this issue by importing and using the definition directly from `@ndn/packet`.

**Comment by zjkmxy** [comment]
Hello.
We recognized this issue recently and I was waiting for a PR to fix it.
If you don't mind, please push a fix replacing the import. I will merge it.
